### ISSUE TITLE
DateFormatter issue

### ISSUE THREAD

**Issue by ywsong219** [tweetjay/NmeaParser#1]
Hi, thanks for the useful library.

I think I found some bug in the code `NmeaParser.swift`. The dateFormat should represent hours by HH (not hh). 

With hh, it was not using the GPS timestamp but it kept using current time which is not from GPS data. 

So, it should be changed like below. I just changed hh to HH and it works fine now.

```
if rawDate.isEmpty {
    dateFormatter.dateFormat = "HHmmss.SSS" // 025816.16
} else {
    dateFormatter.dateFormat = "ddMMyyHHmmss.SSS"
}
```

**Comment by j0d5** [comment]
Hi, thanks for the hint! Will check and change 👍
